[package]
name = "whistled"
description = "Generic GNU/Linux application-level firewall daemon"
authors = ["Aleksa Sarai <cyphar@cyphar.com>"]
version = "0.0.0"
license = "GPL-3.0+"
readme = "README.md"
repository = "https://github.com/cyphar/whistled"

[dependencies]
